spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3307/jpashop
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: root1234
 datasource:
  url: jdbc:h2:tcp://localhost/~/jpashop
  driver-class-name: org.h2.Driver
  username: sa
  password:
 jpa:
   hibernate:
     ddl-auto: create
   properties:
     hibernate.dialect: org.hibernate.dialect.H2Dialect
     hibernate:
       format_sql: true
       default_batch_fetch_size: 100
   show-sql: true